### PR TITLE
Method reference generate link with scroll to text fragment

### LINKED ISSUE #159: Bad anchor in MethodReference
:method:`Symfony\\Component\\OptionsResolver\\OptionsResolver::setDeprecated`

render the follwing link https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/OptionsResolver/OptionsResolver.php#method_setDeprecated

It seems anchor doesn't exist on github.

https://github.com/symfony-tools/docs-builder/blob/11d9d81e3997e771ad1a57eabaa51fc22c500b35/src/Reference/MethodReference.php#L45

I saw URL was `https://api.symfony.com` in past, maybe it was only supported here ? And we have to remove this part ?

Click and go to the good line directly it's a better experience, but I don't know if Github support it (except with L123)

### PR DESCRIPTION
**Pull request by alamirault**
This PR fix #159 if you're ok to use `Scroll-To-Text Fragment`

### CODE REVIEW

**Comment by OskarStark** [comment]
Oh if this works, it would be a nice improvement 👍

**Comment by wouterj** [comment]
Pretty cool and it works nicely in any chromium based browser.

I'm a bit sad that it doesn't work for Firefox yet ([although they are positive](https://mozilla.github.io/standards-positions/#scroll-to-text-fragment)), but given the current anchors also don't work I'm :+1: to use an anchor that at least work for a part of the userbase.

**Comment by OskarStark** [comment]
@javiereguiluz can you please merge and release this PR? Thanks

**Comment by javiereguiluz** [comment]
Thanks Antoine.

**Comment by javiereguiluz** [comment]
Done and released 0.20.6 version: https://github.com/symfony-tools/docs-builder/releases/tag/v0.20.6

**Pull request merged**
